displayName=ChunkBlazer GPU
author=btwinnn
description=Optional greyscale rendering for locked chunks, for use with ChunkBlazer. Not compatible with 117 HD.
tags=chunkblazer,gpu,chunk,locker,draw distance
version=1.0.0
plugins=com.chunkblazer.gpu.ChunkBlazerGpuPlugin
build=standard
